# Generated by Django 6.0.1 on 2026-01-17 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_room_price_alter_hotel_city_alter_hotel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehotel',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_hotel', to='hotel_app.hotel'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotel_app.hotel'),
        ),
    ]
